### ISSUE TITLE
zabbix-agent-extension-mysql/vendor/src: No such file or directory

### ISSUE THREAD

**Issue by bstillman** [zarplata/zabbix-agent-extension-mysql#1]
I'm trying to install, but I get the following during make on CentOS 7.4. 

[root@zabbix-testing ~]# git clone https://github.com/zarplata/zabbix-agent-extension-mysql.git
Cloning into 'zabbix-agent-extension-mysql'...
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 22 (delta 1), reused 20 (delta 1), pack-reused 0
Unpacking objects: 100% (22/22), done.
[root@zabbix-testing ~]# cd zabbix-agent-extension-mysql
[root@zabbix-testing zabbix-agent-extension-mysql]# make
Clean dependencies
rm -rf vendor/*
Clean builded binaries
rm -rf .out/
Done
Fetch dependencies
git submodule update --init
Build
ln -s /root/zabbix-agent-extension-mysql/vendor/ /root/zabbix-agent-extension-mysql/vendor/src
ln: failed to create symbolic link ‘/root/zabbix-agent-extension-mysql/vendor/src’: No such file or directory
make: *** [build] Error 1

Thanks.

**Comment by tears-of-noobs** [comment]
@bstillman Hi. I fixed this issue, please try again build the extension.

**Comment by bstillman** [comment]
That works, now getting:

[root@zabbix-testing zabbix-agent-extension-mysql]# make install
Install
cp .out/zabbix-agent-extension-mysql /usr/bin/zabbix-agent-extension-mysql
cp zabbix-agent-extension-mysql.conf /etc/zabbix/zabbix_agentd.conf.d/zabbix-agent-extension-mysql.conf
cp: cannot create regular file ‘/etc/zabbix/zabbix_agentd.conf.d/zabbix-agent-extension-mysql.conf’: No such file or directory
make: *** [install] Error 1

Should it be: 

cp zabbix-agent-extension-mysql.conf /etc/zabbix/zabbix_agentd.d/zabbix-agent-extension-mysql.conf

Or am I missing something? Thanks.

**Comment by tears-of-noobs** [comment]
@bstillman Yes, you're right. You must copy configuration file with UserParameters into your Zabbix extension directory, maybe in CentOS it  zabbix_agent.d. This error happens because we make software preferably for ArchLinux or Debian based distributions and they have directory with another name -  zabbix_agentd.conf.d

**Comment by bstillman** [comment]
Gotcha. Thanks. On to testing.

**Comment by pigchanc** [comment]
i face this error my os is centos 7.4 and zabbix 3.4
please help me solve it , thanks 

[root@zabbix zabbix-agent-extension-mysql]# make
Clean dependencies
rm -rf vendor/*
Clean builded binaries
rm -rf .out/
Done
Fetch dependencies
git submodule update --init
Submodule path 'vendor/github.com/blacked/go-zabbix': checked out '3c6a95ec4fdc345b48c4e0e5f5c87d48d3fc40b5'
Submodule path 'vendor/github.com/docopt/docopt-go': checked out 'ee0de3bc6815ee19d4a46c7eb90f829db0e014b1'
Submodule path 'vendor/github.com/go-sql-driver/mysql': checked out '1a676ac6e4dce68e9303a1800773861350374a9e'
Submodule path 'vendor/github.com/reconquest/hierr-go': checked out '7d09c0176fd2bb7fd71a4349d1253eef9edb2c5c'
Build
ln -s /root/zabbix-agent-extension-mysql/vendor/ /root/zabbix-agent-extension-mysql/vendor/src
GOPATH="/root/zabbix-agent-extension-mysql/vendor" go build -v -o .out/zabbix-agent-extension-mysql -ldflags "-X main.version="20180412.3_3416614"" *.go
/bin/sh: go: command not found
make: *** [build] Error 127

**Comment by tears-of-noobs** [comment]
@pigchanc This error `/bin/sh: go: command not found` told that you did not install "go" compiler or it placed not in the executable path.
